// قائمة الطلاب المميّزين مع درجاتهم العشوائية
export type FeaturedScore = { name: string; grade: string; section: number; score: number };

export const FEATURED_SCORES: FeaturedScore[] = [
  // رياض ال دحمس - فوق ١٣٠
  { name: "رياض يحيى بن علي آل دحمس", grade: "رابع", section: 1, score: 145 },
  
  // سادس ج - فوقها (فوق 130)
  { name: "أحمد علي احمد آل داهش", grade: "سادس", section: 3, score: 132 },
  { name: "أوس فريد فايع آل فائع", grade: "سادس", section: 3, score: 138 },
  { name: "تميم عبدالرحمن عوض الشهري", grade: "سادس", section: 3, score: 142 },
  { name: "تميم عبدالعزيز محمد القحطاني", grade: "سادس", section: 3, score: 135 },
  { name: "تميم عيسى احمد عسيري", grade: "سادس", section: 3, score: 140 },
  { name: "جياد سعد محمد ال احمد", grade: "سادس", section: 3, score: 133 },
  { name: "حسن خالد حسن الشهري", grade: "سادس", section: 3, score: 137 },
  { name: "حسن فيصل حسن طبيقي", grade: "سادس", section: 3, score: 131 },
  { name: "سعيد عبدالرحمن سعيد عسيري", grade: "سادس", section: 3, score: 139 },
  { name: "رامي عبدالعزيز محمد مكرزي", grade: "سادس", section: 3, score: 136 },
  
  // طلاب إضافيين بدرجات عشوائية
  { name: "أحمد حسام عبد الله الوادعي", grade: "رابع", section: 1, score: 95 },
  { name: "أوس علي محمد الشهري", grade: "رابع", section: 1, score: 78 },
  { name: "بسام محمد بن علي القرني", grade: "رابع", section: 1, score: 102 },
  { name: "تركي عبد العزيز محمد القحطاني", grade: "رابع", section: 2, score: 88 },
  { name: "ثنيان محمد يحيى آل صالح", grade: "رابع", section: 2, score: 112 },
  { name: "خالد هادي فائع عسيري", grade: "رابع", section: 2, score: 65 },
  { name: "سعود يحيى عبد الرحمن محمد", grade: "رابع", section: 3, score: 92 },
  { name: "عبد السلام محمد عبد الله الشهراني", grade: "رابع", section: 3, score: 118 },
  { name: "عمر إبراهيم أحمد عسيري", grade: "رابع", section: 3, score: 75 },
  { name: "فارس عبدالإله عبد الله الحنيشي", grade: "رابع", section: 4, score: 105 },
  { name: "محمد عبد الكريم أحمد علي", grade: "رابع", section: 4, score: 87 },
  { name: "مصعب عبد الكريم معيض القحطاني", grade: "رابع", section: 4, score: 99 },
  { name: "نواف ظافر مسفر العلياني", grade: "رابع", section: 4, score: 81 },
  { name: "نواف عبد الرحمن علي سمعان", grade: "خامس", section: 1, score: 108 },
  { name: "هيثم علي صالح القحطاني", grade: "خامس", section: 1, score: 72 },
  { name: "ياسر مشهور سارح عسيري", grade: "خامس", section: 1, score: 114 },
  { name: "يوسف غازي جميعان الجهني", grade: "خامس", section: 1, score: 90 },
  { name: "أصيل صالح علي القحطاني", grade: "خامس", section: 2, score: 83 },
  { name: "باسم صالح أحمد القرني", grade: "خامس", section: 2, score: 109 },
  { name: "بندر حمد هادي القحطاني", grade: "خامس", section: 2, score: 76 },
  { name: "تركي محمد بن عبد الله العمري", grade: "خامس", section: 2, score: 98 },
  { name: "حسن فارس حسن علي", grade: "خامس", section: 3, score: 89 },
  { name: "سلطان عبد الله بن سعد القحطاني", grade: "خامس", section: 3, score: 115 },
  { name: "عبد العزيز عبد الله أحمد آل حمود", grade: "خامس", section: 3, score: 68 },
  { name: "عبد العزيز محمد بن عبد الله آل ناجي", grade: "خامس", section: 3, score: 103 },
  { name: "عمر محمد بن عبد الله آل ماطر", grade: "خامس", section: 4, score: 91 },
  { name: "محمد عبد الله محمد عسيري", grade: "خامس", section: 4, score: 119 },
  { name: "مهند عامر بن أحمد البناوي", grade: "خامس", section: 4, score: 77 },
  { name: "يحيي عبد الرحمن يحيي عسيري", grade: "سادس", section: 1, score: 106 },
  { name: "هيثم عبد الله بن محمد آل حنش", grade: "سادس", section: 1, score: 84 },
  { name: "بدر فيصل طبيقي", grade: "سادس", section: 1, score: 110 },
  { name: "تركي محمد عطية الزهراني", grade: "سادس", section: 1, score: 73 },
  { name: "راكان يحيى عسيري", grade: "سادس", section: 2, score: 97 },
  { name: "عماد إبراهيم عسيري", grade: "سادس", section: 2, score: 86 },
  { name: "فارس عبد العزيز الشهراني", grade: "سادس", section: 2, score: 117 },
  { name: "أحمد سلطان أحمد عسيري", grade: "سادس", section: 2, score: 69 },
  { name: "إلياس أسامة أحمد المصطفى", grade: "سادس", section: 3, score: 104 },
  { name: "باسل سعود بن حبان الزهراني", grade: "سادس", section: 3, score: 93 },
  { name: "جابر علي جابر علي", grade: "ثالث", section: 1, score: 111 },
  { name: "حاتم محمد عبد العزيز الراقدي", grade: "ثالث", section: 1, score: 79 },
  { name: "سعود ناصر سعيد الشهري", grade: "ثالث", section: 1, score: 100 },
  { name: "علي أحمد علي عسيري", grade: "ثالث", section: 2, score: 85 },
  { name: "عمار محمد عوض المهجري", grade: "ثالث", section: 2, score: 120 },
  { name: "فهد حسن علي عسيري", grade: "ثالث", section: 2, score: 70 },
  { name: "فيصل فهد مفرح القيسي", grade: "ثالث", section: 3, score: 96 },
  { name: "لؤي سلطان يحي الفيفي", grade: "ثالث", section: 3, score: 80 },
  { name: "محمد عبد العزيز محمد القحطاني", grade: "ثاني", section: 1, score: 107 },
  { name: "معن صالح محمد الجواهره", grade: "ثاني", section: 1, score: 74 },
  { name: "مهند أيمن إبراهيم آل مطاعن", grade: "ثاني", section: 1, score: 116 },
  { name: "يوسف محمد عسيري", grade: "ثاني", section: 2, score: 94 },
  { name: "عبد الله سعيد القحطاني", grade: "ثاني", section: 2, score: 113 },
  { name: "آسر سليمان محمد الشبرقي", grade: "ثاني", section: 2, score: 66 },
  { name: "أسامة أحمد إبراهيم عسيري", grade: "ثاني", section: 3, score: 121 },
  { name: "أنس محمد أحمد آل أبو ناصر", grade: "ثاني", section: 3, score: 82 },
  { name: "ثامر محمد قاسم العسيري", grade: "أول", section: 1, score: 101 },
  { name: "ريان علي أحمد الأسمري", grade: "أول", section: 1, score: 91 },
  { name: "سعد محمد سعد عسيري", grade: "أول", section: 1, score: 122 },
  { name: "سعيد محمد سعيد العكاسي", grade: "أول", section: 2, score: 67 },
  { name: "عبد الله أحمد حسن الهيزعي", grade: "أول", section: 2, score: 98 },
  { name: "عزام يحيى رشيد آل فرحان", grade: "أول", section: 2, score: 123 },
  { name: "علي عبد الرحمن محمد آل سليم", grade: "أول", section: 3, score: 71 },
  { name: "عماد عبد الرحمن محمد آل قهيب", grade: "أول", section: 3, score: 125 },
  { name: "فيصل فايز عوض بن ظفره", grade: "أول", section: 3, score: 64 },
  { name: "محمد أحمد محمد الشهري", grade: "خامس", section: 1, score: 128 },
  { name: "ناصر خالد علي عسيري", grade: "خامس", section: 1, score: 62 },
  { name: "نهار نايف عبد الله عسيري", grade: "خامس", section: 2, score: 97 },
];
