// مصدر واحد لبيانات الطلاب الأساسية (الاسم، الصف، الفصل، النقاط).
// يُستخدم كنسخة احتياطية في الذاكرة (server/db.ts) وكذلك عند تعبئة قاعدة البيانات الفارغة.
export type SeedStudent = { fullName: string; grade: string; section: number; score: number };

export const STUDENTS_SEED: SeedStudent[] = [
  { fullName: "أحمد حسام عبد الله الوادعي", grade: "أول", section: 1, score: 65 },
  { fullName: "أوس علي محمد الشهري", grade: "أول", section: 2, score: 89 },
  { fullName: "بسام محمد بن علي القرني", grade: "أول", section: 3, score: 113 },
  { fullName: "تركي عبد العزيز محمد القحطاني", grade: "أول", section: 1, score: 137 },
  { fullName: "ثنيان محمد يحيى آل صالح", grade: "أول", section: 2, score: 65 },
  { fullName: "خالد هادي فائع عسيري", grade: "أول", section: 3, score: 89 },
  { fullName: "سعود يحيى عبد الرحمن محمد", grade: "أول", section: 1, score: 113 },
  { fullName: "عبد السلام محمد عبد الله الشهراني", grade: "أول", section: 2, score: 137 },
  { fullName: "عمر إبراهيم أحمد عسيري", grade: "أول", section: 3, score: 65 },
  { fullName: "فارس عبدالإله عبد الله الحنيشي", grade: "أول", section: 1, score: 89 },
  { fullName: "محمد عبد الكريم أحمد علي", grade: "أول", section: 2, score: 113 },
  { fullName: "مصعب عبد الكريم معيض القحطاني", grade: "أول", section: 3, score: 156 },
  { fullName: "نواف ظافر مسفر العلياني", grade: "أول", section: 1, score: 84 },
  { fullName: "نواف عبد الرحمن علي سمعان", grade: "أول", section: 2, score: 108 },
  { fullName: "هيثم علي صالح القحطاني", grade: "أول", section: 3, score: 132 },
  { fullName: "ياسر مشهور سارح عسيري", grade: "أول", section: 1, score: 156 },
  { fullName: "يوسف غازي جميعان الجهني", grade: "أول", section: 2, score: 84 },
  { fullName: "أصيل صالح علي القحطاني", grade: "أول", section: 3, score: 108 },
  { fullName: "باسم صالح أحمد القرني", grade: "أول", section: 1, score: 132 },
  { fullName: "بندر حمد هادي القحطاني", grade: "أول", section: 2, score: 156 },
  { fullName: "تركي محمد بن عبد الله العمري", grade: "أول", section: 3, score: 84 },
  { fullName: "حسن فارس حسن علي", grade: "أول", section: 1, score: 108 },
  { fullName: "سلطان عبد الله بن سعد القحطاني", grade: "أول", section: 2, score: 151 },
  { fullName: "عبد العزيز عبد الله أحمد آل حمود", grade: "أول", section: 3, score: 79 },
  { fullName: "عبد العزيز محمد بن عبد الله آل ناجي", grade: "أول", section: 1, score: 103 },
  { fullName: "عمر محمد بن عبد الله آل ماطر", grade: "أول", section: 2, score: 127 },
  { fullName: "محمد عبد الله محمد عسيري", grade: "أول", section: 3, score: 151 },
  { fullName: "مهند عامر بن أحمد البناوي", grade: "أول", section: 1, score: 79 },
  { fullName: "يحيي عبد الرحمن يحيي عسيري", grade: "أول", section: 2, score: 103 },
  { fullName: "هيثم عبد الله بن محمد آل حنش", grade: "أول", section: 3, score: 127 },
  { fullName: "بدر فيصل طبيقي", grade: "أول", section: 1, score: 151 },
  { fullName: "تركي محمد عطية الزهراني", grade: "أول", section: 2, score: 79 },
  { fullName: "راكان يحيى عسيري", grade: "أول", section: 3, score: 103 },
  { fullName: "عماد إبراهيم عسيري", grade: "أول", section: 1, score: 146 },
  { fullName: "فارس عبد العزيز الشهراني", grade: "أول", section: 2, score: 74 },
  { fullName: "أحمد سلطان أحمد عسيري", grade: "أول", section: 3, score: 98 },
  { fullName: "إلياس أسامة أحمد المصطفى", grade: "أول", section: 1, score: 122 },
  { fullName: "باسل سعود بن حبان الزهراني", grade: "أول", section: 2, score: 146 },
  { fullName: "جابر علي جابر علي", grade: "أول", section: 3, score: 74 },
  { fullName: "حاتم محمد عبد العزيز الراقدي", grade: "أول", section: 1, score: 98 },
  { fullName: "سعود ناصر سعيد الشهري", grade: "أول", section: 2, score: 122 },
  { fullName: "علي أحمد علي عسيري", grade: "أول", section: 3, score: 146 },
  { fullName: "عمار محمد عوض المهجري", grade: "أول", section: 1, score: 74 },
  { fullName: "فهد حسن علي عسيري", grade: "أول", section: 2, score: 98 },
  { fullName: "فيصل فهد مفرح القيسي", grade: "أول", section: 3, score: 141 },
  { fullName: "لؤي سلطان يحي الفيفي", grade: "أول", section: 1, score: 69 },
  { fullName: "محمد عبد العزيز محمد القحطاني", grade: "أول", section: 2, score: 93 },
  { fullName: "معن صالح محمد الجواهره", grade: "أول", section: 3, score: 117 },
  { fullName: "مهند أيمن إبراهيم آل مطاعن", grade: "أول", section: 1, score: 141 },
  { fullName: "يوسف محمد عسيري", grade: "أول", section: 2, score: 69 },
  { fullName: "عبد الله سعيد القحطاني", grade: "أول", section: 3, score: 93 },
  { fullName: "آسر سليمان محمد الشبرقي", grade: "أول", section: 1, score: 117 },
  { fullName: "أسامة أحمد إبراهيم عسيري", grade: "أول", section: 2, score: 141 },
  { fullName: "أنس محمد أحمد آل أبو ناصر", grade: "أول", section: 3, score: 69 },
  { fullName: "ثامر محمد قاسم العسيري", grade: "أول", section: 1, score: 93 },
  { fullName: "ريان علي أحمد الأسمري", grade: "أول", section: 2, score: 136 },
  { fullName: "سعد محمد سعد عسيري", grade: "أول", section: 3, score: 160 },
  { fullName: "سعيد محمد سعيد العكاسي", grade: "أول", section: 1, score: 88 },
  { fullName: "عبد الله أحمد حسن الهيزعي", grade: "أول", section: 2, score: 112 },
  { fullName: "عزام يحيى رشيد آل فرحان", grade: "أول", section: 3, score: 136 },
  { fullName: "علي عبد الرحمن محمد آل سليم", grade: "أول", section: 1, score: 160 },
  { fullName: "عماد عبد الرحمن محمد آل قهيب", grade: "أول", section: 2, score: 88 },
  { fullName: "فيصل فايز عوض بن ظفره", grade: "أول", section: 3, score: 112 },
  { fullName: "محمد أحمد محمد الشهري", grade: "أول", section: 1, score: 136 },
  { fullName: "ناصر خالد علي عسيري", grade: "أول", section: 2, score: 160 },
  { fullName: "نهار نايف عبد الله عسيري", grade: "أول", section: 3, score: 88 },
  { fullName: "أبان عبد الله سعيد عسيري", grade: "أول", section: 1, score: 131 },
  { fullName: "أحمد رائد أحمد الزهراني", grade: "أول", section: 2, score: 155 },
  { fullName: "أحمد عبد الكريم أحمد هيجان", grade: "أول", section: 3, score: 83 },
  { fullName: "باسل علي عوض آل عيسى", grade: "أول", section: 1, score: 107 },
  { fullName: "بدر عبد الكريم أحمد هيجان", grade: "أول", section: 2, score: 131 },
  { fullName: "جسار عائض محمد عسيري", grade: "أول", section: 3, score: 155 },
  { fullName: "حاتم علي حنبص آل موسى", grade: "ثاني", section: 1, score: 83 },
  { fullName: "خالد سعيد بن عبد الله الأسمري", grade: "ثاني", section: 2, score: 107 },
  { fullName: "رائد خالد علي عسيري", grade: "ثاني", section: 3, score: 131 },
  { fullName: "سطام محمد عبد الله القحطاني", grade: "ثاني", section: 1, score: 155 },
  { fullName: "سعد سعيد بن عبد الله القحطاني", grade: "ثاني", section: 2, score: 83 },
  { fullName: "عبد الرحمن ريان عبد الرحمن اليحيا", grade: "ثاني", section: 3, score: 126 },
  { fullName: "علي محمد علي آل منيف", grade: "ثاني", section: 1, score: 150 },
  { fullName: "عمر حسين سفر آل ثابت", grade: "ثاني", section: 2, score: 78 },
  { fullName: "فيصل فارس مشبب الأحمري", grade: "ثاني", section: 3, score: 102 },
  { fullName: "محمد مريع سعد هباش", grade: "ثاني", section: 1, score: 126 },
  { fullName: "مشعل توفيق سعيد الأحمري", grade: "ثاني", section: 2, score: 150 },
  { fullName: "ناصر عبد الله ناصر الشهراني", grade: "ثاني", section: 3, score: 78 },
  { fullName: "ناصر محمد ناصر الشهراني", grade: "ثاني", section: 1, score: 102 },
  { fullName: "يزن محمد عبد الرحمن عسيري", grade: "ثاني", section: 2, score: 126 },
  { fullName: "يزيد محمد سعيد الشطفان", grade: "ثاني", section: 3, score: 150 },
  { fullName: "إياس أحمد سليمان الجابري", grade: "ثاني", section: 1, score: 78 },
  { fullName: "تركي هادي علي القحطاني", grade: "ثاني", section: 2, score: 121 },
  { fullName: "راكان محمد سعد الوادعي", grade: "ثاني", section: 3, score: 145 },
  { fullName: "رياض علي يحيى الزيادي", grade: "ثاني", section: 1, score: 73 },
  { fullName: "زياد علي بن سعود عسيري", grade: "ثاني", section: 2, score: 97 },
  { fullName: "سطام عبد العزيز رفيدي الأسمري", grade: "ثاني", section: 3, score: 121 },
  { fullName: "عارف علي أحمد آل نيران", grade: "ثاني", section: 1, score: 145 },
  { fullName: "علي صالح خلوفة الأحمري", grade: "ثاني", section: 2, score: 73 },
  { fullName: "علي عبد الله علي آل هماس", grade: "ثاني", section: 3, score: 97 },
  { fullName: "عمر عبد الله عمر عمير", grade: "ثاني", section: 1, score: 121 },
  { fullName: "فارس سعيد عبد الله", grade: "ثاني", section: 2, score: 145 },
  { fullName: "كنان علي رفيدي", grade: "ثاني", section: 3, score: 73 },
  { fullName: "محمد علي بن حسن", grade: "ثاني", section: 1, score: 116 },
  { fullName: "نواف عادل بن ناصر", grade: "ثاني", section: 2, score: 140 },
  { fullName: "هتان محمد بن علي زامل", grade: "ثاني", section: 3, score: 68 },
  { fullName: "يحيى علي بن يحيى", grade: "ثاني", section: 1, score: 92 },
  { fullName: "باسل محمد سعيد القحطاني", grade: "ثاني", section: 2, score: 116 },
  { fullName: "بدر ماجد علي العسيري", grade: "ثاني", section: 3, score: 140 },
  { fullName: "تميم طارق حسن القحطاني", grade: "ثاني", section: 1, score: 68 },
  { fullName: "تميم مبارك بن فهد القحطاني", grade: "ثاني", section: 2, score: 92 },
  { fullName: "جاسر أحمد ابن صالح عسيري", grade: "ثاني", section: 3, score: 116 },
  { fullName: "حمود عبدالرحمن جرمان الأسمري", grade: "ثاني", section: 1, score: 140 },
  { fullName: "رويد عبدالله سعيد محروس", grade: "ثاني", section: 2, score: 68 },
  { fullName: "زياد عبدالله محمد الشهراني", grade: "ثاني", section: 3, score: 111 },
  { fullName: "سلمان محمد ناصر آل أحمد", grade: "ثاني", section: 1, score: 135 },
  { fullName: "عبد الإله أحمد حسن الهيزعي", grade: "ثاني", section: 2, score: 159 },
  { fullName: "عبد الله علي سعيد القحطاني", grade: "ثاني", section: 3, score: 87 },
  { fullName: "عز محمد مرعي القرني", grade: "ثاني", section: 1, score: 111 },
  { fullName: "علي أحمد ماطر آل شواف", grade: "ثاني", section: 2, score: 135 },
  { fullName: "علي محمد علي الشديدي", grade: "ثاني", section: 3, score: 159 },
  { fullName: "علي منصور عامر القرني", grade: "ثاني", section: 1, score: 87 },
  { fullName: "عمر أحمد ماطر آل شواف", grade: "ثاني", section: 2, score: 111 },
  { fullName: "مؤيد عبد الرحمن علي الشهري", grade: "ثاني", section: 3, score: 135 },
  { fullName: "مراد سعيد عبد الرحمن عسيري", grade: "ثاني", section: 1, score: 159 },
  { fullName: "مشعل عبدالله يحي الشهراني", grade: "ثاني", section: 2, score: 106 },
  { fullName: "معاذ ظافر عايض القحطاني", grade: "ثاني", section: 3, score: 130 },
  { fullName: "نواف ماجد حمود الحسام", grade: "ثاني", section: 1, score: 154 },
  { fullName: "هشام محمد منصور العسيري", grade: "ثاني", section: 2, score: 82 },
  { fullName: "هيثم محمد إبراهيم آل مطاعم", grade: "ثاني", section: 3, score: 106 },
  { fullName: "وسام سعيد حسين الأحمري", grade: "ثاني", section: 1, score: 130 },
  { fullName: "يحيى جبران يحيى آل جحدل", grade: "ثاني", section: 2, score: 154 },
  { fullName: "يزن أمين بن إبراهيم علوان", grade: "ثاني", section: 3, score: 82 },
  { fullName: "يزيد يحيى سعد عسيري", grade: "ثاني", section: 1, score: 106 },
  { fullName: "أسامة مهند  سعيد عسيري", grade: "ثاني", section: 2, score: 130 },
  { fullName: "بتال علي سابر الأسمري", grade: "ثاني", section: 3, score: 154 },
  { fullName: "بتال محمد فايع عسيري", grade: "ثاني", section: 1, score: 101 },
  { fullName: "جسار سلطان سعد الأحمري", grade: "ثاني", section: 2, score: 125 },
  { fullName: "حسين علي حسين آل عدينان", grade: "ثاني", section: 3, score: 149 },
  { fullName: "خالد سعد محمد عسيري", grade: "ثاني", section: 1, score: 77 },
  { fullName: "رائد أحمد علي القحطاني", grade: "ثاني", section: 2, score: 101 },
  { fullName: "راكان عبدالله أحمد الشهري", grade: "ثاني", section: 3, score: 125 },
  { fullName: "زايد عبدالله مبارك الشهراني", grade: "ثاني", section: 1, score: 149 },
  { fullName: "زياد محمد حسين القحطاني", grade: "ثاني", section: 2, score: 77 },
  { fullName: "سعود تركي علي الأسمري", grade: "ثاني", section: 3, score: 101 },
  { fullName: "سعيد علي ابن يحي بن شبعان", grade: "ثاني", section: 1, score: 125 },
  { fullName: "سعيد محمد حسن قحطاني", grade: "ثاني", section: 2, score: 149 },
  { fullName: "سلمان مريع سعد هباش", grade: "ثالث", section: 3, score: 96 },
  { fullName: "سند ناصر محمد علاي", grade: "ثالث", section: 1, score: 120 },
  { fullName: "سيف ناصر محمد علاي", grade: "ثالث", section: 2, score: 144 },
  { fullName: "عبد الرحمن علي بن عوض الوادعي", grade: "ثالث", section: 3, score: 72 },
  { fullName: "عبدالله محمد ابن عبد الله  آل ناجي", grade: "ثالث", section: 1, score: 96 },
  { fullName: "عبد الملك فارس ابن عبد الله سرحان", grade: "ثالث", section: 2, score: 120 },
  { fullName: "عزام محمد علي عسيري", grade: "ثالث", section: 3, score: 144 },
  { fullName: "فراس ياسر فرحان آل عامر", grade: "ثالث", section: 1, score: 72 },
  { fullName: "محمد أنس  محمد مجدوع", grade: "ثالث", section: 2, score: 96 },
  { fullName: "محمد عادل محمد عسيري", grade: "ثالث", section: 3, score: 120 },
  { fullName: "محمد عبد العزيز محمد أبو سبعة", grade: "ثالث", section: 1, score: 144 },
  { fullName: "مشهور مسفر سعيد آل كعبان", grade: "ثالث", section: 2, score: 91 },
  { fullName: "نايف غازي عوض القحطاني", grade: "ثالث", section: 3, score: 115 },
  { fullName: "وسام حافظ أحمد العسكري", grade: "ثالث", section: 1, score: 139 },
  { fullName: "أوس يحي عايض عسيري", grade: "ثالث", section: 2, score: 67 },
  { fullName: "إياس فائع علي عسيري", grade: "ثالث", section: 3, score: 91 },
  { fullName: "باسل جبران حسن القحطاني", grade: "ثالث", section: 1, score: 115 },
  { fullName: "حمزه عبد الله حسن الوداعي", grade: "ثالث", section: 2, score: 139 },
  { fullName: "خالد سلطان محمد العمري", grade: "ثالث", section: 3, score: 67 },
  { fullName: "خالد عبد الرحمن أحمد عبدلي", grade: "ثالث", section: 1, score: 91 },
  { fullName: "خالد علي محمد عياشي", grade: "ثالث", section: 2, score: 115 },
  { fullName: "سعد مصطفى سعد القحطاني", grade: "ثالث", section: 3, score: 139 },
  { fullName: "سلمان عبد الله حسين بالحارث", grade: "ثالث", section: 1, score: 86 },
  { fullName: "سند خالد أحمد الخالدي", grade: "ثالث", section: 2, score: 110 },
  { fullName: "صقر عوض محمد القحطاني", grade: "ثالث", section: 3, score: 134 },
  { fullName: "عادل علي سعد الشهراني", grade: "ثالث", section: 1, score: 158 },
  { fullName: "عبد العزيز محمد جربوع الشهراني", grade: "ثالث", section: 2, score: 86 },
  { fullName: "فهد عبد الرحمن علي الزهراني", grade: "ثالث", section: 3, score: 110 },
  { fullName: "فيصل سعود لاحق مسود", grade: "ثالث", section: 1, score: 134 },
  { fullName: "كرم خالد راتب الزرير", grade: "ثالث", section: 2, score: 158 },
  { fullName: "محمد راشد علي آل هتيله", grade: "ثالث", section: 3, score: 86 },
  { fullName: "محمد عامر راضي الدغامين", grade: "ثالث", section: 1, score: 110 },
  { fullName: "محمد علي أحمد عسيري", grade: "ثالث", section: 2, score: 134 },
  { fullName: "مهند محمد عبده السيد", grade: "ثالث", section: 3, score: 81 },
  { fullName: "هادي حسين هادي الوداعي", grade: "ثالث", section: 1, score: 105 },
  { fullName: "يزيد بن محمد بن سعد العامري", grade: "ثالث", section: 2, score: 129 },
  { fullName: "اياس عبدالرحمن محمدالياس الازوري", grade: "ثالث", section: 3, score: 153 },
  { fullName: "بدر حسن عثمان القرني", grade: "ثالث", section: 1, score: 81 },
  { fullName: "تميم سعد محمد الأسمري", grade: "ثالث", section: 2, score: 105 },
  { fullName: "تميم محمد عبدالرحمن الاسمري", grade: "ثالث", section: 3, score: 129 },
  { fullName: "جسار علي محمد شايع", grade: "ثالث", section: 1, score: 153 },
  { fullName: "جسار محمد عبدالله شائع", grade: "ثالث", section: 2, score: 81 },
  { fullName: "حازم عائض محمد عسيري", grade: "ثالث", section: 3, score: 105 },
  { fullName: "رويد ناصر محمد عسيري", grade: "ثالث", section: 1, score: 129 },
  { fullName: "ريان الحسن زبن الله الحارثي", grade: "ثالث", section: 2, score: 76 },
  { fullName: "زياد عبدالله مسفر الغامدي", grade: "ثالث", section: 3, score: 100 },
  { fullName: "سلمان حاتم ناصر المعاوي", grade: "ثالث", section: 1, score: 124 },
  { fullName: "عبدالله نايف عبده الأسمري", grade: "ثالث", section: 2, score: 148 },
  { fullName: "علي طاهر محمد الشهري", grade: "ثالث", section: 3, score: 76 },
  { fullName: "علي محمد على بهكلي", grade: "ثالث", section: 1, score: 100 },
  { fullName: "علي ناصر علي عسيري", grade: "ثالث", section: 2, score: 124 },
  { fullName: "عمر مفرح زايد البناوي", grade: "ثالث", section: 3, score: 148 },
  { fullName: "فارس محمد عبدالهادي العمري", grade: "ثالث", section: 1, score: 76 },
  { fullName: "فهد خالد فهد القحطاني", grade: "ثالث", section: 2, score: 100 },
  { fullName: "قصي سعيد حسن العمري", grade: "ثالث", section: 3, score: 124 },
  { fullName: "محمد يحي مسعود الفيفي", grade: "ثالث", section: 1, score: 71 },
  { fullName: "محمد يحيى جابر عسيري", grade: "ثالث", section: 2, score: 95 },
  { fullName: "نايف عبدالعزيز محمد الزميلي", grade: "ثالث", section: 3, score: 119 },
  { fullName: "نايف علي يحي الشهري", grade: "ثالث", section: 1, score: 143 },
  { fullName: "هتان علي سعد القرني", grade: "ثالث", section: 2, score: 71 },
  { fullName: "يحيى محمد يحي القحطاني", grade: "ثالث", section: 3, score: 95 },
  { fullName: "منذر حمد عبدالله حاضر", grade: "ثالث", section: 1, score: 119 },
  { fullName: "نواف سعد بن محمد آل فضيل", grade: "ثالث", section: 2, score: 143 },
  { fullName: "نواف يحي عبدالرحمن محمد", grade: "ثالث", section: 3, score: 71 },
  { fullName: "أحمد عبدالرحمن عامر القرني", grade: "ثالث", section: 1, score: 95 },
  { fullName: "الياس يزيد موسى آل حيدر", grade: "ثالث", section: 2, score: 119 },
  { fullName: "بدر شتوي معيض القحطاني", grade: "ثالث", section: 3, score: 66 },
  { fullName: "تركي عبدالعزيز صالح الشهري", grade: "ثالث", section: 1, score: 90 },
  { fullName: "تميم سعيد ناصر عسيري", grade: "ثالث", section: 2, score: 114 },
  { fullName: "تميم محمد بن سعد الشهري", grade: "ثالث", section: 3, score: 138 },
  { fullName: "تيام سعيد بن محمد عسيري", grade: "ثالث", section: 1, score: 66 },
  { fullName: "خالد عبدالله بن عائض آل مرعان", grade: "ثالث", section: 2, score: 90 },
  { fullName: "خالد وليد محمد عسيري", grade: "رابع", section: 4, score: 114 },
  { fullName: "راشد بن  أحمد بن مغرم بن عبدالله  ال محمد العمري", grade: "رابع", section: 1, score: 138 },
  { fullName: "رامي عبدالله بن صالح الوابل", grade: "رابع", section: 2, score: 66 },
  { fullName: "زياد عبدالله سعيد الغامدي", grade: "رابع", section: 3, score: 90 },
  { fullName: "زياد محمد بن مشبب آل محمد", grade: "رابع", section: 4, score: 114 },
  { fullName: "سعود عبدالعزيز جودالله عسيري", grade: "رابع", section: 1, score: 157 },
  { fullName: "صالح عبدالله سعد العمري", grade: "رابع", section: 2, score: 85 },
  { fullName: "عبدالاله عبدالله معدي الشهري", grade: "رابع", section: 3, score: 109 },
  { fullName: "عبدالعزيز بن محمد بن ظافر بن محمد ال حبيط", grade: "رابع", section: 4, score: 133 },
  { fullName: "عبدالله حسام عبدالله الوادعي", grade: "رابع", section: 1, score: 157 },
  { fullName: "عبدالمجيد احمد ابن سعيد آل مالح", grade: "رابع", section: 2, score: 85 },
  { fullName: "عبدالمجيد عبدالرحمن ابن حسن الراشدي", grade: "رابع", section: 3, score: 109 },
  { fullName: "عدي علي ضيف الله القرني", grade: "رابع", section: 4, score: 133 },
  { fullName: "عمر بن علي بن يحيى آل قراش الشهراني", grade: "رابع", section: 1, score: 157 },
  { fullName: "فهد علي محمد عياشي", grade: "رابع", section: 2, score: 85 },
  { fullName: "فهد شريف عبده الأسمري", grade: "رابع", section: 3, score: 109 },
  { fullName: "كريم حذيفه محمد السليمي", grade: "رابع", section: 4, score: 152 },
  { fullName: "مانع محمد مانع آل محيا", grade: "رابع", section: 1, score: 80 },
  { fullName: "أحمد ابراهيم علي عسيري", grade: "رابع", section: 2, score: 104 },
  { fullName: "أحمد محمد أحمد آل مشافي", grade: "رابع", section: 3, score: 128 },
  { fullName: "المنذر علي محمد معيض", grade: "رابع", section: 4, score: 152 },
  { fullName: "اياد ابراهيم مرعي الربعي", grade: "رابع", section: 1, score: 80 },
  { fullName: "بتال عبدالمجيد عثمان ال جراده", grade: "رابع", section: 2, score: 104 },
  { fullName: "تميم نايف عبدالله عسيري", grade: "رابع", section: 3, score: 128 },
  { fullName: "جاسر محمد جاسر الشهري", grade: "رابع", section: 4, score: 152 },
  { fullName: "حسام صالح هادي عسيري", grade: "رابع", section: 1, score: 80 },
  { fullName: "زايد سلطان عبدالله ناحي", grade: "رابع", section: 2, score: 104 },
  { fullName: "سلمان عبدالله بن عبدالرحمن عسيري", grade: "رابع", section: 3, score: 147 },
  { fullName: "سيف سعد محمد سعران", grade: "رابع", section: 4, score: 75 },
  { fullName: "سيف محمد بن ابراهيم فقيه", grade: "رابع", section: 1, score: 99 },
  { fullName: "عبدالله سعد سعيد بن حمه", grade: "رابع", section: 2, score: 123 },
  { fullName: "عبدالله عبداللطيف محفوظ محمد", grade: "رابع", section: 3, score: 147 },
  { fullName: "عبدالله محمد عبدالله الشهراني", grade: "رابع", section: 4, score: 75 },
  { fullName: "علي عجيبي راشد الحربي", grade: "رابع", section: 1, score: 99 },
  { fullName: "محمد سعيد محمد القحطاني", grade: "رابع", section: 2, score: 123 },
  { fullName: "محمد عبدالملك ابن محمد ال سلمان", grade: "رابع", section: 3, score: 147 },
  { fullName: "محمد علي خلف الزهراني", grade: "رابع", section: 4, score: 75 },
  { fullName: "نواف احمد حسن الهيزعي", grade: "رابع", section: 1, score: 99 },
  { fullName: "نواف منيف ضيف الله الغامدي", grade: "رابع", section: 2, score: 142 },
  { fullName: "يوسف اسامه احمد المصطفى", grade: "رابع", section: 3, score: 70 },
  { fullName: "أحمد علي احمد آل داهش", grade: "رابع", section: 4, score: 94 },
  { fullName: "أوس فريد فايع آل فائع", grade: "رابع", section: 1, score: 118 },
  { fullName: "تميم عبدالرحمن عوض الشهري", grade: "رابع", section: 2, score: 142 },
  { fullName: "تميم عبدالعزيز محمد القحطاني", grade: "رابع", section: 3, score: 70 },
  { fullName: "تميم عيسى احمد عسيري", grade: "رابع", section: 4, score: 94 },
  { fullName: "جياد سعد محمد ال احمد", grade: "رابع", section: 1, score: 118 },
  { fullName: "حسن خالد حسن الشهري", grade: "رابع", section: 2, score: 142 },
  { fullName: "حسن فيصل حسن طبيقي", grade: "رابع", section: 3, score: 70 },
  { fullName: "سعيد عبدالرحمن سعيد عسيري", grade: "رابع", section: 4, score: 94 },
  { fullName: "رامي عبدالعزيز محمد مكرزي", grade: "رابع", section: 1, score: 137 },
  { fullName: "ريان حامد بن مجدوع القرني", grade: "رابع", section: 2, score: 65 },
  { fullName: "زايد حسن مريع آل حمدان", grade: "رابع", section: 3, score: 89 },
  { fullName: "زيد ماهر مصلح الشامي", grade: "رابع", section: 4, score: 113 },
  { fullName: "عبدالاله عايض عبدالله عسيري", grade: "رابع", section: 1, score: 137 },
  { fullName: "عبدالملك حسن سليمان الفيفي", grade: "رابع", section: 2, score: 65 },
  { fullName: "عبدالوهاب حسن احمد ال طالع", grade: "رابع", section: 3, score: 89 },
  { fullName: "علي احمد علي عسيري", grade: "رابع", section: 4, score: 113 },
  { fullName: "فاضل حمود بن محمد جابر", grade: "رابع", section: 1, score: 137 },
  { fullName: "لورنس حجري راجح الشهري", grade: "رابع", section: 2, score: 65 },
  { fullName: "مازن فايز عبده الشهري", grade: "رابع", section: 3, score: 89 },
  { fullName: "محمد علي محمد الخثعمي", grade: "رابع", section: 4, score: 132 },
  { fullName: "محمد منصور جرمان الأسمري", grade: "رابع", section: 1, score: 156 },
  { fullName: "مشعل محمد يزيد غزواني", grade: "رابع", section: 2, score: 84 },
  { fullName: "ناصر عادل بن ناصر بدوي", grade: "رابع", section: 3, score: 108 },
  { fullName: "نواف سعيد بن عبدالله بن يعن الله", grade: "رابع", section: 4, score: 132 },
  { fullName: "تركي عبدالرحمن يحي الحدري", grade: "رابع", section: 1, score: 156 },
  { fullName: "تميم عبدالله على الأسمري", grade: "رابع", section: 2, score: 84 },
  { fullName: "تميم فيصل سعد آل شيبان", grade: "رابع", section: 3, score: 108 },
  { fullName: "راشد بن عيسى بن علي القشر", grade: "رابع", section: 4, score: 132 },
  { fullName: "زياد ابن صالح ابن مبارك ال علوان", grade: "رابع", section: 1, score: 156 },
  { fullName: "زياد بن هليل بن عبدالله العتيبي", grade: "رابع", section: 2, score: 84 },
  { fullName: "سلطان علي سعيد القحطاني", grade: "خامس", section: 3, score: 127 },
  { fullName: "صالح عوض بن علي آل عباس", grade: "خامس", section: 4, score: 151 },
  { fullName: "عائض محمد بن عائض الشهري", grade: "خامس", section: 1, score: 79 },
  { fullName: "عادل علي عبدالله الشهري", grade: "خامس", section: 2, score: 103 },
  { fullName: "عادل مفرح زايد البناوي", grade: "خامس", section: 3, score: 127 },
  { fullName: "عبدالله محمد عبدالله شائع", grade: "خامس", section: 4, score: 151 },
  { fullName: "علي عبدالله علي العمري", grade: "خامس", section: 1, score: 79 },
  { fullName: "عمر عبدالعزيز علي البكري", grade: "خامس", section: 2, score: 103 },
  { fullName: "عمر ماجد عبدالله الشهري", grade: "خامس", section: 3, score: 127 },
  { fullName: "فهد عبدالرحمن محمد آل سليم", grade: "خامس", section: 4, score: 151 },
  { fullName: "مشاري سعد شائع القحطاني", grade: "خامس", section: 1, score: 79 },
  { fullName: "منصور عبدالناصر محمد الشهري", grade: "خامس", section: 2, score: 122 },
  { fullName: "موسى يزيد موسى آل حيدر", grade: "خامس", section: 3, score: 146 },
  { fullName: "نايف تركي بن معيض آل سالم", grade: "خامس", section: 4, score: 74 },
  { fullName: "أسامه سعد محمد عسيري", grade: "خامس", section: 1, score: 98 },
  { fullName: "إبراهيم محمد عادل البعداني", grade: "خامس", section: 2, score: 122 },
  { fullName: "بتال عبدالعزيز محمد القحطاني", grade: "خامس", section: 3, score: 146 },
  { fullName: "بدر على بن ابراهيم آل نشبه", grade: "خامس", section: 4, score: 74 },
  { fullName: "بسام سعيد علي آل سعد", grade: "خامس", section: 1, score: 98 },
  { fullName: "تركي علي موسى الشهراني", grade: "خامس", section: 2, score: 122 },
  { fullName: "خالد سعيد يحي ال شويل", grade: "خامس", section: 3, score: 146 },
  { fullName: "سلطان عبدالعزيز ابرهيم فقيه", grade: "خامس", section: 4, score: 74 },
  { fullName: "سلمان حسن محمد مغرم", grade: "خامس", section: 1, score: 117 },
  { fullName: "سلمان علي خلف الزهراني", grade: "خامس", section: 2, score: 141 },
  { fullName: "طلال خالد بن عايض آل جازع", grade: "خامس", section: 3, score: 69 },
  { fullName: "عبدالاله محمد تركي الشهري", grade: "خامس", section: 4, score: 93 },
  { fullName: "عبدالكريم علي احمد عسيري", grade: "خامس", section: 1, score: 117 },
  { fullName: "عبدالله علي عبدالله الاسمري", grade: "خامس", section: 2, score: 141 },
  { fullName: "عبدالله علي عبدالله القرني", grade: "خامس", section: 3, score: 69 },
  { fullName: "عبدالله موسى علي العسيري", grade: "خامس", section: 4, score: 93 },
  { fullName: "علي عبدالله علي سبار", grade: "خامس", section: 1, score: 117 },
  { fullName: "محمد عبدالله محمد المالكي", grade: "خامس", section: 2, score: 141 },
  { fullName: "محمد فارس بن مسفر العمورات", grade: "خامس", section: 3, score: 69 },
  { fullName: "معن يحي بن منصور عسيري", grade: "خامس", section: 4, score: 112 },
  { fullName: "أحمد علي احمد عسيري", grade: "خامس", section: 1, score: 136 },
  { fullName: "احمد يحي الحسين عسيري", grade: "خامس", section: 2, score: 160 },
  { fullName: "بسام علي احمد عسيري", grade: "خامس", section: 3, score: 88 },
  { fullName: "تميم بندر احمد الاحمري", grade: "خامس", section: 4, score: 112 },
  { fullName: "تميم علي عيسى عسيري", grade: "خامس", section: 1, score: 136 },
  { fullName: "تميم مشرف ضيف الله الشهري", grade: "خامس", section: 2, score: 160 },
  { fullName: "خالد احمد حسن الهيزعي", grade: "خامس", section: 3, score: 88 },
  { fullName: "رياض يحيى بن علي آل دحمس", grade: "خامس", section: 4, score: 112 },
  { fullName: "سطام متعب حريق الأحمري", grade: "خامس", section: 1, score: 136 },
  { fullName: "سعد دخيل الله سعد الشمراني", grade: "خامس", section: 2, score: 160 },
  { fullName: "سعود عبدالله يوسف آل قاسم", grade: "خامس", section: 3, score: 107 },
  { fullName: "عبدالوهاب غازي محمد ناصر", grade: "خامس", section: 4, score: 131 },
  { fullName: "علي سيف علي محمد", grade: "خامس", section: 1, score: 155 },
  { fullName: "ماجد حسين عبد الرحمن الطايل", grade: "خامس", section: 2, score: 83 },
  { fullName: "مالك محمد سالم الشغيبي", grade: "خامس", section: 3, score: 107 },
  { fullName: "مجاهد علي عامر القرني", grade: "خامس", section: 4, score: 131 },
  { fullName: "محمد خالد محمد آل مسرع", grade: "خامس", section: 1, score: 155 },
  { fullName: "مشاري ظافر حميدي أل لغر", grade: "خامس", section: 2, score: 83 },
  { fullName: "مشاري محمد عوض المهجري", grade: "خامس", section: 3, score: 107 },
  { fullName: "مهند عبدالواحد بن احمد الزهراني", grade: "خامس", section: 4, score: 131 },
  { fullName: "نواف محمد بن سعيد الشهراني", grade: "خامس", section: 1, score: 155 },
  { fullName: "نواف يزيد يحي النعمي", grade: "خامس", section: 2, score: 102 },
  { fullName: "وسام هادي فائع عسيري", grade: "خامس", section: 3, score: 126 },
  { fullName: "أبي ابراهيم احمد ناجي", grade: "خامس", section: 4, score: 150 },
  { fullName: "أمين أحمد عبدالقادر أبوجبل", grade: "خامس", section: 1, score: 78 },
  { fullName: "أنس يحي ناصر الزهراني", grade: "خامس", section: 2, score: 102 },
  { fullName: "تميم حسن ابراهيم آل جبار", grade: "خامس", section: 3, score: 126 },
  { fullName: "تميم عايض محمد البشري", grade: "خامس", section: 4, score: 150 },
  { fullName: "تميم علي حمدي أل حلبوب", grade: "خامس", section: 1, score: 78 },
  { fullName: "خالد حسن مانع ال عمير", grade: "خامس", section: 2, score: 102 },
  { fullName: "خالد يعقوب اسماعيل جوابره", grade: "خامس", section: 3, score: 126 },
  { fullName: "راكان عبدالله يحي عسيري", grade: "خامس", section: 4, score: 150 },
  { fullName: "صالح ماجد صالح آل سعدان", grade: "خامس", section: 1, score: 97 },
  { fullName: "عبدالاله عبدالله علي آل كاسي", grade: "خامس", section: 2, score: 121 },
  { fullName: "عبدالله احمد محمد آل حنش", grade: "خامس", section: 3, score: 145 },
  { fullName: "عبدالله مشعل عبدالله ابومسمار", grade: "خامس", section: 4, score: 73 },
  { fullName: "عمر علي ظافر الشهراني", grade: "خامس", section: 1, score: 97 },
  { fullName: "غراس عمر علي آل عمر", grade: "خامس", section: 2, score: 121 },
  { fullName: "فهد حسين سعيد القحطاني", grade: "سادس", section: 2, score: 145 },
  { fullName: "محمد إسماعيل محمد البشري", grade: "سادس", section: 3, score: 73 },
  { fullName: "محمد فهد عبدالله ناحي", grade: "سادس", section: 1, score: 97 },
  { fullName: "نهيان محمد عبداله مفرح", grade: "سادس", section: 2, score: 121 },
  { fullName: "هشام حسين بن سعيد عامر", grade: "سادس", section: 3, score: 145 },
  { fullName: "يامن ابراهيم علي عسيري", grade: "سادس", section: 1, score: 92 },
  { fullName: "احمد عبدالكريم احمد علي", grade: "سادس", section: 2, score: 116 },
  { fullName: "البراء محمد أحمد عسيري", grade: "سادس", section: 3, score: 140 },
  { fullName: "بتال سعود سعيد الاسمري", grade: "سادس", section: 1, score: 68 },
  { fullName: "جسار طارق حسن القحطاني", grade: "سادس", section: 2, score: 92 },
  { fullName: "خالد سعد عبدالرحمن العمري", grade: "سادس", section: 3, score: 116 },
  { fullName: "زياد قاسم عسيري", grade: "سادس", section: 1, score: 140 },
  { fullName: "دويل محمد دويل بالحامض", grade: "سادس", section: 2, score: 68 },
  { fullName: "سعيد سفر سعيد الشهراني", grade: "سادس", section: 3, score: 92 },
  { fullName: "ظافر محمد ظافر الشهري", grade: "سادس", section: 1, score: 116 },
  { fullName: "عبدالعزيز سعيد يحي ال شويل", grade: "سادس", section: 2, score: 140 },
  { fullName: "عبدالله محمد بن عبدالله العمري", grade: "سادس", section: 3, score: 87 },
  { fullName: "علي محمد علي آل عليه", grade: "سادس", section: 1, score: 111 },
  { fullName: "علي محمد منصور مدخلي", grade: "سادس", section: 2, score: 135 },
  { fullName: "فارس فايز عبدالله الشهري", grade: "سادس", section: 3, score: 159 },
  { fullName: "فارس محمد ظافر الشهري", grade: "سادس", section: 1, score: 87 },
  { fullName: "فيصل صالح خلوفه الاحمري", grade: "سادس", section: 2, score: 111 },
  { fullName: "مؤيد سعيد سعد الغامدي", grade: "سادس", section: 3, score: 135 },
  { fullName: "مشعل محمد مهدي القحطاني", grade: "سادس", section: 1, score: 159 },
  { fullName: "وسام يعن الله سعيد الشهري", grade: "سادس", section: 2, score: 87 },
  { fullName: "آسر محمد بن علي آل نازح", grade: "سادس", section: 3, score: 111 },
  { fullName: "أحمد عبدالله سعد العمري", grade: "سادس", section: 1, score: 135 },
  { fullName: "احمد ابراهيم احمد عسيري", grade: "سادس", section: 2, score: 82 },
  { fullName: "المثنى محمد شعشوع الاسمري", grade: "سادس", section: 3, score: 106 },
  { fullName: "بتال سعيد عوظه آل واكد", grade: "سادس", section: 1, score: 130 },
  { fullName: "تركي عبدالله بن سعد القحطاني", grade: "سادس", section: 2, score: 154 },
  { fullName: "تميم حذيفه محمد السليمي", grade: "سادس", section: 3, score: 82 },
  { fullName: "تميم عبدالله ظافر ال هيال", grade: "سادس", section: 1, score: 106 },
  { fullName: "خالد بن وليد يحيى القحطاني", grade: "سادس", section: 2, score: 130 },
  { fullName: "سلطان موسى بن يحي بن حيان", grade: "سادس", section: 3, score: 154 },
  { fullName: "صقر محمد جابر الشهري", grade: "سادس", section: 1, score: 82 },
  { fullName: "طلال فهد ابراهيم عسيري", grade: "سادس", section: 2, score: 106 },
  { fullName: "عبدالمجيد محمد علي العمري", grade: "سادس", section: 3, score: 130 },
  { fullName: "عمر عبدالعزيزعبدالله ال زميع القحطاني", grade: "سادس", section: 1, score: 77 },
  { fullName: "فيصل ابن ماجد بن علي بن احمد العسيري", grade: "سادس", section: 2, score: 101 },
  { fullName: "محمد سعيد عبدالله القحطاني", grade: "سادس", section: 3, score: 125 },
  { fullName: "محمد عبدالله بن سعد القحطاني", grade: "سادس", section: 1, score: 149 },
  { fullName: "مشعل خالد بن عبدالله عسيري", grade: "سادس", section: 2, score: 77 },
  { fullName: "نادر عبدالعزيز علي القرني", grade: "سادس", section: 3, score: 101 },
  { fullName: "نواف عبدالله ابن متعب آل هادي", grade: "سادس", section: 1, score: 125 },
  { fullName: "يامن علي عبدالله الالمعي", grade: "سادس", section: 2, score: 149 },
  { fullName: "أنس محمد يحي ال عمار", grade: "سادس", section: 3, score: 77 },
  { fullName: "ابراهيم احمد ابراهيم عسيري", grade: "سادس", section: 1, score: 101 },
  { fullName: "ابراهيم زهير محمد ال عاص", grade: "سادس", section: 2, score: 125 },
  { fullName: "اسماعيل محمد اسماعيل حمدان", grade: "سادس", section: 3, score: 72 },
  { fullName: "جبران عبدالله مبارك الشهراني", grade: "سادس", section: 1, score: 96 },
  { fullName: "خالد عبدالله بن مسفر الزهيري", grade: "سادس", section: 2, score: 120 },
  { fullName: "خالد علي محمد الشهري", grade: "سادس", section: 3, score: 144 },
  { fullName: "خالد فيصل علي القحطاني", grade: "سادس", section: 1, score: 72 },
  { fullName: "خالد يحي محمد ال شويل", grade: "سادس", section: 2, score: 96 },
  { fullName: "عبدالرحمن ظافر بن عبدالرحمن آل مضحي", grade: "سادس", section: 3, score: 120 },
  { fullName: "عبدالرحمن فهد عثمان الشهراني", grade: "سادس", section: 1, score: 144 },
  { fullName: "عبدالعزيز زكريا محمد عريبي", grade: "سادس", section: 2, score: 72 },
  { fullName: "عبدالله احمد محمد عسيري", grade: "سادس", section: 3, score: 96 },
  { fullName: "عبدالله بن علي بن عبدالله علي القاسمي عسيري", grade: "سادس", section: 1, score: 120 },
  { fullName: "فارس حسين سعد القحطاني", grade: "سادس", section: 2, score: 67 },
  { fullName: "فهد على يحي الشهراني", grade: "سادس", section: 3, score: 91 },
  { fullName: "فواز ظافر بن عبدالرحمن آل مضحي", grade: "سادس", section: 1, score: 115 },
  { fullName: "فيصل مريع سعد هباش", grade: "سادس", section: 2, score: 139 },
  { fullName: "محمد أيمن ابراهيم آل مطاعن", grade: "سادس", section: 3, score: 67 },
  { fullName: "محمد احمد محمد عسيري", grade: "سادس", section: 1, score: 91 },
  { fullName: "محمد طاهر محمد الشهري", grade: "سادس", section: 2, score: 115 },
  { fullName: "مشاري سعيد مانع الاحمري", grade: "سادس", section: 3, score: 139 },
  { fullName: "مهند زياد بن محمد العسكري", grade: "سادس", section: 1, score: 67 },
  { fullName: "نادر سالم مهدي ال معمر", grade: "سادس", section: 2, score: 91 },
  { fullName: "يزن بشير بن يحي الفقيه", grade: "سادس", section: 3, score: 115 },
];
